[wso2.devportal_service.devportal]
DEVPORTAL_PORT = 9443


# Sample configurations
[wso2.devportal_service.devportal.datasourceConfiguration]
description = ""
url = ""
username = ""
password = ""
validationTimeout = 0
testQuery = ""

[wso2.devportal_service.devportal.throttleConfig]
enableUnlimitedTier = true

